# Generated by Django 2.2.4 on 2019-08-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100, verbose_name='Article')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('article', models.FileField(blank=True, upload_to='features_articles/')),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=100, verbose_name='Journal')),
                ('abbr_title', models.CharField(blank=True, default='N/A', max_length=100, verbose_name='Abbr. Title')),
                ('issn_print', models.CharField(max_length=20, verbose_name='ISSN Print')),
                ('issn_online', models.CharField(max_length=20, verbose_name='ISSN Online')),
                ('frequency', models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Frequency')),
                ('chief_editor', models.CharField(max_length=50, verbose_name='chief editor')),
                ('origin_country', models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Origin')),
                ('language', models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Language')),
                ('publisher', models.CharField(blank=True, default='N/A', max_length=50, verbose_name='Publisher')),
                ('journal_info', models.TextField(max_length=2000, verbose_name='Info')),
                ('indexing_factor', models.CharField(max_length=20, verbose_name='Index Factor')),
                ('journal_cover', models.ImageField(upload_to='journals/', verbose_name='Cover')),
                ('journal_thumb', models.ImageField(upload_to='journals/', verbose_name='Thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='TopEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('editor_name', models.CharField(max_length=50, verbose_name='Name')),
                ('editor_info', models.CharField(max_length=1000, verbose_name='Info')),
                ('profile', models.ImageField(blank=True, upload_to='editors/')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_name', models.CharField(max_length=50, verbose_name='Volume name')),
                ('volume_year', models.PositiveIntegerField(verbose_name='Year')),
                ('issue_name', models.CharField(max_length=20, verbose_name='Issue')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Journal')),
            ],
        ),
        migrations.CreateModel(
            name='JournalFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.PositiveIntegerField(verbose_name='USD')),
                ('inr', models.PositiveIntegerField(verbose_name='INR')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Journal')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('editor_name', models.CharField(max_length=50, verbose_name='Name')),
                ('editor_info', models.CharField(max_length=1000, verbose_name='Info')),
                ('profile', models.ImageField(blank=True, upload_to='editors/')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Journal')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(max_length=40, verbose_name='Type')),
                ('article_name', models.CharField(max_length=100, verbose_name='Article')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('article', models.FileField(upload_to='articles/')),
                ('publish_date', models.DateField()),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Volume')),
            ],
        ),
    ]
